[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day1"
path = "src/day1.rs"


[[bin]]
name = "day2"
path = "src/day2.rs"

[dependencies]
itertools = "0.13.0"
regex = "1.11.1"
text_io = "0.1.12"
